---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - drone.ocean.dev
  resources:
  - droneservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drone.ocean.dev
  resources:
  - droneservers/finalizers
  verbs:
  - update
- apiGroups:
  - drone.ocean.dev
  resources:
  - droneservers/status
  verbs:
  - get
  - patch
  - update
