apiVersion: drone.ocean.dev/v1alpha1
kind: DroneServer
metadata:
  labels:
    app.kubernetes.io/name: drone-ci-operator
    app.kubernetes.io/managed-by: kustomize
  name: droneserver-sample
spec:
  # TODO(user): Add fields here
